# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antimoji < Formula
  desc "High-performance emoji detection and removal CLI tool"
  homepage "https://github.com/jamesainslie/antimoji"
  version "0.9.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.9/antimoji_0.9.9_darwin_amd64.tar.gz"
      sha256 "a5923bb3d946b23d7f5933be78c957c21dcc7ec54020394abcf67c69792d0c5a"

      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.9/antimoji_0.9.9_darwin_arm64.tar.gz"
      sha256 "36ed1b64d9b786cd566b6721c5d035be19e781d51c65ec55a1105553c7a6b6ae"

      def install
        bin.install "antimoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.9/antimoji_0.9.9_linux_amd64.tar.gz"
      sha256 "d344a1f36e7f698ca490ec5c7e0d70a5797302d4ebaea67864e0e0b91b2d2e7f"
      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.9/antimoji_0.9.9_linux_arm64.tar.gz"
      sha256 "b8723e48c4a4e8f2698cd2d009e77e39fc12c0761ac8d0e903bd51674418699f"
      def install
        bin.install "antimoji"
      end
    end
  end

  def caveats
    <<~EOS
      Antimoji is a high-performance emoji detection and removal tool.

      Basic usage:
        antimoji scan .                    # Scan for emojis
        antimoji clean --backup .          # Remove emojis with backup
        antimoji generate --type=ci-lint . # Generate allowlist config
        antimoji setup-lint --mode=zero-tolerance  # Setup automated linting

      Documentation: https://github.com/jamesainslie/antimoji
    EOS
  end

  test do
    system "#{bin}/antimoji", "version"

    # Test basic functionality
    (testpath/"test.txt").write("Hello world! 😀")
    output = shell_output("#{bin}/antimoji scan #{testpath}/test.txt")
    assert_match "1", output
  end
end
