# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antimoji < Formula
  desc "High-performance emoji detection and removal CLI tool"
  homepage "https://github.com/jamesainslie/antimoji"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.4/antimoji_0.9.4_darwin_amd64.tar.gz"
      sha256 "dba73eb0a4abca11706648612d25f06eb94d0523b913032c17489919c8519ad9"

      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.4/antimoji_0.9.4_darwin_arm64.tar.gz"
      sha256 "c107a99fe0020c898e84ac1bd3768195d8ca9ea2aa505f742422f87126977800"

      def install
        bin.install "antimoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.4/antimoji_0.9.4_linux_amd64.tar.gz"
      sha256 "39859e587d280da4c4adf79a935b1db611e5faad926bcc7d2e5f38f456f53781"
      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.4/antimoji_0.9.4_linux_arm64.tar.gz"
      sha256 "5a4da015865dd35234f4464a3b0c4f267f0f1ec65deae17309013dedc4534567"
      def install
        bin.install "antimoji"
      end
    end
  end

  test do
    system "#{bin}/antimoji --version"
  end
end
