# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antimoji < Formula
  desc "High-performance emoji detection and removal CLI tool"
  homepage "https://github.com/jamesainslie/antimoji"
  version "0.9.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.17/antimoji_0.9.17_darwin_amd64.tar.gz"
      sha256 "d61094162670c28ab68bde40be0bafa6abd96f240844efa671366c3a61f8049a"

      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.17/antimoji_0.9.17_darwin_arm64.tar.gz"
      sha256 "828ca680c6398a67c9163c6b933faba1e4af9bd51f952fa57885d79784d9c5c7"

      def install
        bin.install "antimoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.17/antimoji_0.9.17_linux_amd64.tar.gz"
      sha256 "cec49e84f96f16ba3b3c36bdbe3693435a76be4cc53bda57b2db13be0572769d"
      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.17/antimoji_0.9.17_linux_arm64.tar.gz"
      sha256 "15af68ab00292f0011a46a2907c6a77c205b2dcef49a692b1992e1a5dd63ec73"
      def install
        bin.install "antimoji"
      end
    end
  end

  def caveats
    <<~EOS
      Antimoji is a high-performance emoji detection and removal tool.

      Basic usage:
        antimoji scan .                    # Scan for emojis
        antimoji clean --backup .          # Remove emojis with backup
        antimoji generate --type=ci-lint . # Generate allowlist config
        antimoji setup-lint --mode=zero-tolerance  # Setup automated linting

      Documentation: https://github.com/jamesainslie/antimoji
    EOS
  end

  test do
    system "#{bin}/antimoji", "version"

    # Test basic functionality
    (testpath/"test.txt").write("Hello world! 😀")
    output = shell_output("#{bin}/antimoji scan #{testpath}/test.txt")
    assert_match "1", output
  end
end
