# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Antimoji < Formula
  desc "High-performance emoji detection and removal CLI tool"
  homepage "https://github.com/jamesainslie/antimoji"
  version "0.9.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.18/antimoji_0.9.18_darwin_amd64.tar.gz"
      sha256 "6cab3c3a26c2e32a726094f17a49f891159e2b3b94565989494a5bb7e2a019e8"

      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.18/antimoji_0.9.18_darwin_arm64.tar.gz"
      sha256 "592bb94bf160da166e16ae8bc56c95654a9b4abb72b047e05074e1c6991a54b0"

      def install
        bin.install "antimoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.18/antimoji_0.9.18_linux_amd64.tar.gz"
      sha256 "f3ede7f858ff7aaabf6d43964cc5f87be2fb459f4ff6acdc6619a031160fd26b"
      def install
        bin.install "antimoji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jamesainslie/antimoji/releases/download/v0.9.18/antimoji_0.9.18_linux_arm64.tar.gz"
      sha256 "f5ebaabe5f699c04d174029de57e2bd9b755b05a1685869f8094401758f36e87"
      def install
        bin.install "antimoji"
      end
    end
  end

  def caveats
    <<~EOS
      Antimoji is a high-performance emoji detection and removal tool.

      Basic usage:
        antimoji scan .                    # Scan for emojis
        antimoji clean --backup .          # Remove emojis with backup
        antimoji generate --type=ci-lint . # Generate allowlist config
        antimoji setup-lint --mode=zero-tolerance  # Setup automated linting

      Documentation: https://github.com/jamesainslie/antimoji
    EOS
  end

  test do
    system "#{bin}/antimoji", "version"

    # Test basic functionality
    (testpath/"test.txt").write("Hello world! 😀")
    output = shell_output("#{bin}/antimoji scan #{testpath}/test.txt")
    assert_match "1", output
  end
end
